info.app:
  name: HMPPS Court Case Service Api
  version: 1.0

spring:
  application:
    name: hmpps-court-case-service-api
  codec:
    max-in-memory-size: 10MB

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  security:
    oauth2:
      client:
        registration:
          community-api-client:
            client-name: community-api-client
            client-id: ${community-api-client-id:community-api-client}
            client-secret: ${community-api-client-secret:clientsecret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
          offender-assessments-api-client:
            client-name: offender-assessments-api-client
            client-id: ${offender-assessments-api.client-id}
            client-secret: ${offender-assessments-api.client-secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
          prison-api-client:
            client-name: prison-api-client
            client-id: ${prison-api-client-id:prison-api-client}
            client-secret: ${prison-api-client-secret:clientsecret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
          manage-offences-api-client:
            client-name: manage-offences-api-client
            client-id: ${manage-offences-api-client-id:manage-offences-api-client}
            client-secret: ${manage-offences-api-client-secret:clientsecret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
          court-case-and-delius-api-client:
            client-name: court-case-and-delius-api-client
            client-id: ${court-case-and-delius-api-client-id:court-case-and-delius-api-client}
            client-secret: ${court-case-and-delius-api-client-secret:clientsecret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
          flipt:
            base-url: ${flipt-api-url:url}
            api-key: ${flipt-api-key:api-key}
          domain-event-and-delius-api-client:
            client-name: domain-event-and-delius-api-client
            client-id: ${domain-event-and-delius-api-client-id:domain-event-and-delius-api-client}
            client-secret: ${domain-event-and-delius-api-client-secret:clientsecret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
          hmpps-document-management-api-client:
            client-name: hmpps-document-management-api-client
            client-id: ${hmpps-document-management-api-client:hmpps-document-management-api-client}
            client-secret: ${hmpps-document-management-api-client-secret:clientsecret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            provider: nomis-oauth-service
        provider:
          nomis-oauth-service:
            token-uri: ${nomis-oauth.base-url}/oauth/token
      resourceserver:
        jwt:
          issuer-uri: ${nomis-oauth.issuer-base-url:${nomis-oauth.base-url}}/issuer
          jwk-set-uri: ${nomis-oauth.base-url}/.well-known/jwks.json

database:
  schema:
    name: hmpps_court_case_service

r2dbc:
  migrate:
    resources:
      - resource-path: classpath:db/migration/premigration/*.sql
      - resource-path: classpath:db/migration/*.sql
    migrations-schema: hmpps_court_case_service

server:
  port: 8080
  servlet:
    context-path: /
  forward-headers-strategy: native
  tomcat:
    remoteip:
      remote-ip-header: x-forwarded-for
      protocol-header: x-forwarded-proto
      internal-proxies: 10\.\d{1,3}\.\d{1,3}\.\d{1,3}|192\.168\.\d{1,3}\.\d{1,3}|169\.254\.\d{1,3}\.\d{1,3}|127\.\d{1,3}\.\d{1,3}\.\d{1,3}|172\.1[6-9]{1}\.\d{1,3}\.\d{1,3}|172\.2[0-9]{1}\.\d{1,3}\.\d{1,3}|172\.3[0-1]{1}\.\d{1,3}\.\d{1,3}|0:0:0:0:0:0:0:1|::1|100\.6[4-9]\.\d{1,3}\.\d{1,3}|100\.[7-9][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.1[0-1][0-9]{1}\.\d{1,3}\.\d{1,3}|100\.12[0-7]\.\d{1,3}\.\d{1,3}
  shutdown: graceful
  error:
    include-message: always

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: 'info, health'
  endpoint:
    health:
      cache:
        time-to-live: 2000ms
      show-components: always
      show-details: always
      probes:
        enabled: true
    info:
      cache:
        time-to-live: 2000ms
